[build]
  command = "ng build && ng run verssat:server"
  publish = "dist/verssat"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
