services:
  - type: web
    name: verssat
    env: node
    branch: main
    buildCommand: |
      npm install -g @angular/cli
      npm install
      npm run build:ssr
    startCommand: npm run serve:ssr
    plan: free
